### ISSUE TITLE
Diagnostic Plot Not Displaying

### ISSUE THREAD

**Issue by mishranurag** [georgebv/pyextremes-notebooks#1]
Hi

Thank you for the library. I am trying to create the diagnostic plot and saving them as png file. However, the following command 
`    model.plot_diagnostic(alpha=0.05)
`
gives only following output

`
(<Figure size 768x768 with 4 Axes>,
 (<Axes: title={'center': 'Return value plot'}, xlabel='Return period', ylabel='Precipitation Value'>,
  <Axes: title={'center': 'Probability density plot'}, xlabel='Precipitation Value', ylabel='Probability density'>,
  <Axes: title={'center': 'Q-Q plot'}, xlabel='Theoretical', ylabel='Observed'>,
  <Axes: title={'center': 'P-P plot'}, xlabel='Theoretical', ylabel='Observed'>))
`

I could not find a simple way to saving these plots as png files either.

Sincerely
Anurag

**Comment by georgebv** [comment]
You are getting matplotlib Figure. I suggest reading documentation for matplotlib on how to work with Figure objects.
